export const mockMenu = [
  {
    id: 85,
    name: 'Women',
    url: '/women',
    image: '',
    children: [
      {
        id: 86,
        name: 'Clothes',
        url: '/#',
        image: '',
        children: [
          {
            id: 87,
            name: 'T-shirts',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 88,
            name: 'Leggings',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 89,
            name: 'Shorts',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 90,
            name: 'Tops',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 91,
            name: 'Dresses',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 92,
            name: 'Jackets',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 93,
            name: 'Pants',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 94,
            name: 'Underwear',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 95,
        name: 'Accessories',
        url: '/#',
        image: '',
        children: [
          {
            id: 96,
            name: 'Backpacks',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 97,
            name: 'Bags',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 98,
            name: 'Hair Accessories',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 99,
            name: 'Hats',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 100,
            name: 'Scarves & Wraps',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 101,
        name: 'Footwear',
        url: '/#',
        image: '',
        children: [
          {
            id: 102,
            name: 'Trainers',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 103,
            name: 'Running',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 104,
            name: 'Sandals',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 105,
            name: 'Essentials',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 106,
            name: 'Socks',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 107,
        name: 'Brands',
        url: '/#',
        image: '',
        children: [
          {
            id: 108,
            name: 'Nike',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 109,
            name: 'Puma',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 110,
            name: 'Converse',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 111,
            name: 'Vans',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 112,
            name: 'Aramis',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 113,
            name: 'Reserva',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 114,
    name: 'Men',
    url: '/men',
    image: '',
    children: [
      {
        id: 115,
        name: 'Clothes',
        url: '/#',
        image: '',
        children: [
          {
            id: 116,
            name: 'T-shirts',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 117,
            name: 'Leggings',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 118,
            name: 'Shorts',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 119,
            name: 'Tops',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 120,
            name: 'Dresses',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 121,
            name: 'Jackets',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 122,
            name: 'Pants',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 123,
            name: 'Underwear',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 124,
        name: 'Accessories',
        url: '/#',
        image: '',
        children: [
          {
            id: 125,
            name: 'Backpacks',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 126,
            name: 'Bags',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 127,
            name: 'Hair Accessories',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 128,
            name: 'Hats',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 129,
            name: 'Scarves & Wraps',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 130,
        name: 'Footwear',
        url: '/#',
        image: '',
        children: [
          {
            id: 131,
            name: 'Trainers',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 132,
            name: 'Running',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 133,
            name: 'Sandals',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 134,
            name: 'Essentials',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 135,
            name: 'Socks',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 136,
        name: 'Brands',
        url: '/#',
        image: '',
        children: [
          {
            id: 137,
            name: 'Nike',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 138,
            name: 'Puma',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 139,
            name: 'Converse',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 140,
            name: 'Vans',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 141,
            name: 'Aramis',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 142,
            name: 'Reserva',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 143,
    name: 'Girl',
    url: '#',
    image: '',
    children: [
      {
        id: 144,
        name: 'Clothes',
        url: '/#',
        image: '',
        children: [
          {
            id: 145,
            name: 'T-shirts',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 146,
            name: 'Leggings',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 147,
            name: 'Shorts',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 148,
            name: 'Tops',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 149,
            name: 'Dresses',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 150,
            name: 'Jackets',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 151,
            name: 'Pants',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 152,
            name: 'Underwear',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 153,
        name: 'Accessories',
        url: '/#',
        image: '',
        children: [
          {
            id: 154,
            name: 'Backpacks',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 155,
            name: 'Bags',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 156,
            name: 'Hair Accessories',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 157,
            name: 'Hats',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 158,
            name: 'Scarves & Wraps',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 159,
        name: 'Footwear',
        url: '/#',
        image: '',
        children: [
          {
            id: 160,
            name: 'Trainers',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 161,
            name: 'Running',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 162,
            name: 'Sandals',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 163,
            name: 'Essentials',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 164,
            name: 'Socks',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 165,
        name: 'Brands',
        url: '/#',
        image: '',
        children: [
          {
            id: 166,
            name: 'Nike',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 167,
            name: 'Puma',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 168,
            name: 'Converse',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 169,
            name: 'Vans',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 170,
            name: 'Aramis',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 171,
            name: 'Reserva',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 172,
    name: 'Boy',
    url: '#',
    image: '',
    children: [
      {
        id: 173,
        name: 'Clothes',
        url: '/#',
        image: '',
        children: [
          {
            id: 174,
            name: 'T-shirts',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 175,
            name: 'Leggings',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 176,
            name: 'Shorts',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 177,
            name: 'Tops',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 178,
            name: 'Dresses',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 179,
            name: 'Jackets',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 180,
            name: 'Pants',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 97,
            name: 'Underwear',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 181,
        name: 'Accessories',
        url: '/#',
        image: '',
        children: [
          {
            id: 182,
            name: 'Backpacks',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 183,
            name: 'Bags',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 184,
            name: 'Hair Accessories',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 185,
            name: 'Hats',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 186,
            name: 'Scarves & Wraps',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 187,
        name: 'Footwear',
        url: '/#',
        image: '',
        children: [
          {
            id: 188,
            name: 'Trainers',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 189,
            name: 'Running',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 190,
            name: 'Sandals',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 191,
            name: 'Essentials',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 192,
            name: 'Socks',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
      {
        id: 193,
        name: 'Brands',
        url: '/#',
        image: '',
        children: [
          {
            id: 194,
            name: 'Nike',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 195,
            name: 'Puma',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 196,
            name: 'Converse',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 197,
            name: 'Vans',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 198,
            name: 'Aramis',
            url: '/#',
            image: '',
            children: [],
          },
          {
            id: 199,
            name: 'Reserva',
            url: '/#',
            image: '',
            children: [],
          },
        ],
      },
    ],
  },
  {
    id: 527,
    name: 'New arrivals',
    url: '/#',
    image: '',
    children: [],
  },
  {
    id: 200,
    name: 'Sale',
    url: '/',
    image: '',
    children: [],
  },
]
